### ISSUE TITLE
Investigate wrong rdma_get_cm_event

### ISSUE THREAD

**Issue by LasseThostrup** [DataManagementLab/rdma-manager#10]
If tests are run many times (e.g. 100), it seems like the event channel is not cleaned up and eventually fails.

terminate called after throwing an instance of 'std::runtime_error'
  what():  rdma_get_cm_event returned event did not match type!
Aborted

**Comment by mjasny** [comment]
fixed by fd513e6d42052d575b6dd8486ca11f9876bcda19
